### ISSUE TITLE
Problem running on Ubuntu 20.04 Focal (x86_64)

### ISSUE THREAD

**Issue by jmarkow** [labjack/labjack-ljm-python#15]
I ran the labjack installation script from the website and am now attempting to access the labjack via ljm in Python – using a T7-Pro over USB. All works well in Windows, but on Ubuntu I get the following error message when attempting to set up PeriodicStreamOut

`AttributeError: /usr/local/lib/libLabJackM.so: undefined symbol: LJM_PeriodicStreamOut`

The code is pretty simple, happy to post if that would help debug this.

**Comment by sjarman28** [comment]
The issue is likely that your LJM version is too old. `LJM_PeriodicStreamOut` is only available in LJM 1.21 and later. LJM 1.21 is currently only available in our beta LJM installer:
https://labjack.com/pages/support?doc=/software-driver/installer-downloads/ljm-software-installers-t4-t7-digit/#header-three-5e65q

**Comment by jmarkow** [comment]
That fixed it! Can confirm the 2020_03_30 beta works. Apologies for the oversight on my part.
