### ISSUE TITLE
how can I setup UART on T7?

### ISSUE THREAD

**Issue by hchaudhary1** [labjack/labjack-ljm-python#2]
Hi I just purchased an T7 Pro. I need to use UART.
Is it possible to control UART TX and RX on T7 via python?

If not, what else can I do?

**Comment by rolsen** [comment]
Yes, you can control UART via this python wrapper to LJM. You can use the [13.7 Asynchronous Serial](https://labjack.com/support/datasheets/t-series/digital-io/asynchronous-serial) section of the T-Series Datasheet to understand what registers to read/write.

You can use the more\asynch\uart_loopback_test.c example of the [LJM C examples](https://labjack.com/support/software/examples/ljm/c) as a starting example. Since LJM is used by this Python wrapper, it's a simple translation between the two—it's really just the order of which registers are read/written that matters.

**Comment by hchaudhary1** [comment]
thanks. will try
